import type { RewardItem } from "./types"

export const REWARDS_CATALOG: RewardItem[] = [
  {
    id: "lambo-huracan",
    category: "Supercar Drive",
    title: "LAMBORGHINI HURACÁN",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/cars/lambo-side.png",
    available: true,
    bookingCarId: "lambo-huracan",
    bookingLaps: 5,
  },
  {
    id: "ferrari-488",
    category: "Supercar Drive",
    title: "FERRARI 488 GTB",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/cars/ferrari-side.png",
    available: true,
    bookingCarId: "ferrari-488",
    bookingLaps: 5,
  },
  {
    id: "mclaren-gt",
    category: "Supercar Drive",
    title: "MCLAREN 720S",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/cars/mclaren-side.png",
    available: true,
    bookingCarId: "mclaren-gt",
    bookingLaps: 5,
  },
  {
    id: "porsche-911",
    category: "Supercar Drive",
    title: "PORSCHE 911 GT3",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/cars/gt3-side.png",
    available: true,
    bookingCarId: "porsche-911-gt3",
    bookingLaps: 5,
  },
  {
    id: "supercar-photoshoot",
    category: "Media Experience",
    title: "SUPERCAR PHOTOSHOOT",
    specs: "5 HD photos with a supercar",
    creditsRequired: 1000,
    imageUrl: "/experience/highlight-photoshoot.png",
    available: true,
    addonType: "photoshoot",
  },
  {
    id: "instagram-reel",
    category: "Media Experience",
    title: "INSTAGRAM 4K REEL",
    specs: "30-second drone & cockpit reel",
    creditsRequired: 2000,
    imageUrl: "/images/cockpit/porsche-cockpit.png",
    available: true,
    addonType: "reel",
  },
]
