import type { RewardItem } from "./types"

export const REWARDS_CATALOG: RewardItem[] = [
  {
    id: "lambo-huracan",
    category: "Supercar Drive",
    title: "LAMBORGHINI HURACÁN",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/fleet/huracan.jpg",
    available: true,
    bookingCarId: "lambo-huracan",
    bookingLaps: 5,
  },
  {
    id: "ferrari-488",
    category: "Supercar Drive",
    title: "FERRARI",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/fleet/ferrari.jpg",
    available: true,
    bookingCarId: "ferrari-488",
    bookingLaps: 5,
  },
  {
    id: "mclaren-gt",
    category: "Supercar Drive",
    title: "MCLAREN",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/fleet/mclaren.jpg",
    available: true,
    bookingCarId: "mclaren-gt",
    bookingLaps: 5,
  },
  {
    id: "porsche-911",
    category: "Supercar Drive",
    title: "PORSCHE 911",
    specs: "5 laps · 2 km per lap",
    creditsRequired: 25000,
    imageUrl: "/fleet/porsche-911.jpg",
    available: true,
    bookingCarId: "porsche-911-gt3",
    bookingLaps: 5,
  },
  {
    id: "supercar-photoshoot",
    category: "Experience",
    title: "SUPERCAR PHOTOSHOOT",
    specs: "5 HD photos with a supercar",
    creditsRequired: 1000,
    imageUrl: "/fleet/photoshoot.jpg",
    available: true,
    addonType: "photoshoot",
  },
  {
    id: "instagram-reel",
    category: "Experience",
    title: "INSTAGRAM REEL",
    specs: "30-second reel with a supercar",
    creditsRequired: 2000,
    imageUrl: "/fleet/instagram-reel.jpg",
    available: true,
    addonType: "reel",
  },
]
